plugins {
    id 'java'
    id 'org.spongepowered.gradle.vanilla' version '0.2.1'
}

allprojects {
    apply plugin: 'java'
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'
    apply plugin: 'idea'
    version = mod_version
    group = maven_group

    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    repositories {
        mavenCentral()
        maven { url "https://repo.spongepowered.org/repository/maven-public/"}
        mavenLocal()
    }

    tasks.withType(GenerateModuleMetadata) {
        enabled = false
    }
}

subprojects {
}

repositories {
    mavenLocal()
}

minecraft {
    version(minecraft_version)
}

dependencies {
    compileOnly group:'org.spongepowered', name:'mixin', version:'0.8.5'
    implementation('com.epherical.octo-economy-api:OctoEconomyApi:1.2.0-1.20.1')
    annotationProcessor('org.jetbrains:annotations:23.0.0')

    implementation 'com.zaxxer:HikariCP:5.0.1'
    implementation 'mysql:mysql-connector-j:8.0.33'
}

sourceSets {
    main {
        resources {
            srcDirs += [
                    "src/main/generated"
            ]
        }
    }
}
